name: Test
on: push    
jobs:
 test:
   timeout-minutes: 60
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
       node-version: '14.x'
   - name: Install dependencies
     run: yarn
   - name: Install Playwright
     run: npx playwright install
   - name: Run Playwright tests
     run: yarn playwright test
